[package]
name = "MediHelpAPI"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5"
csv = "1.3.1"
serde = "1.0.2"

[dependencies.reqwest]
version = "0.12.23"
features = ["charset"]

[dependencies.chrono]
version = "0.4.42"
features = ["serde"]